### ISSUE TITLE
Sleep issues?

### ISSUE THREAD

**Issue by rchavezj** [MaximumQuiet/ryzentosh#4]
Lot of people had issues getting their amd system to sleep. I wanted to check if you had similar experience.

**Comment by maxkusnetsov** [comment]
> Lot of people had issues getting their amd system to sleep. I wanted to check if you had similar experience.

Yeah, my sleep was completely broken (freezing after trying to sleep), but recently I figured out how to make it work:
1. First of all, read the following guide: https://dortania.github.io/OpenCore-Post-Install/universal/sleep.html
2. Then do the USB mapping (read more https://dortania.github.io/OpenCore-Post-Install/usb/)
3. Then configure the BIOS options: Legacy USB - on, Wake On Lan - off, Wake On USB - off (cause this can prevent the system to sleep)
4. Reconnect all of your USB3 devices to **USB3** ports (not a USB2)
5. Check the existence of apps prevent the system to sleep by the confirmations something like "Are you sure to exit?"

These steps helped me. I have only one issue with sleep right now - I can't manage to make Wake on Lan work. But sleep is working correctly.

**Comment by rchavezj** [comment]
Did you need to redo the process inside windows 10 and/or managed to configure the bios options and usb mapping inside macosx?

**Comment by maxkusnetsov** [comment]
@rchavezj No, I configured options by just entering the BIOS setup at the PC start. BIOS options affect any OS booted on a PC.
And USB mapping need only on macOS because Windows already works correctly with USB. I configured it by USB-Map kext.
